# Generated by Django 4.2.7 on 2025-08-28 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0014_alter_entreprise_options_alter_offrestage_entreprise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternKpiEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name="date d'évaluation")),
                ('delivery_satisfaction_rate', models.DecimalField(decimal_places=2, help_text='Note sur 5 pour le taux de satisfaction des livrables (poids: 25%)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='taux de satisfaction des livrables')),
                ('deadline_respect_rate', models.DecimalField(decimal_places=2, help_text='Note sur 5 pour le respect des délais (poids: 20%)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='respect des délais')),
                ('learning_capacity', models.DecimalField(decimal_places=2, help_text="Note sur 5 pour la capacité d'apprentissage (poids: 15%)", max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name="capacité d'apprentissage")),
                ('initiative_taking', models.DecimalField(decimal_places=2, help_text="Note sur 5 pour la prise d'initiatives (poids: 10%)", max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name="prise d'initiatives")),
                ('professional_behavior', models.DecimalField(decimal_places=2, help_text='Note sur 5 pour le comportement professionnel (poids: 15%)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='comportement en entreprise et conduite')),
                ('adaptability', models.DecimalField(decimal_places=2, help_text="Note sur 5 pour l'adaptabilité (poids: 15%)", max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='adaptabilité au changement')),
                ('total_score', models.DecimalField(decimal_places=2, editable=False, help_text='Score total calculé automatiquement sur 5', max_digits=4, verbose_name='score total')),
                ('interpretation', models.CharField(choices=[('elevé', 'Potentiel élevé'), ('bon', 'Bon potentiel'), ('moyen', 'Potentiel moyen'), ('à renforcer', 'Potentiel à renforcer')], editable=False, help_text='Catégorie de potentiel déterminée automatiquement', max_length=20, verbose_name='interprétation')),
                ('comments', models.TextField(blank=True, verbose_name='commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'rh'}, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='évaluateur')),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'stagiaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='stagiaire')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_evaluations', to='shared.stage', verbose_name='stage')),
            ],
            options={
                'verbose_name': 'évaluation KPI stagiaire',
                'verbose_name_plural': 'évaluations KPI stagiaires',
                'db_table': 'intern_kpi_evaluations',
                'ordering': ['-evaluation_date', '-created_at'],
                'unique_together': {('intern', 'stage', 'evaluation_date')},
            },
        ),
    ]
