# Generated by Django 5.0.2 on 2025-07-05 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_notification_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('entreprise', models.CharField(max_length=200, verbose_name='entreprise')),
                ('specialite', models.CharField(max_length=200, verbose_name='spécialité')),
                ('niveau', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('ingenieur', 'Ingénieur'), ('doctorat', 'Doctorat')], default='licence', max_length=20, verbose_name='niveau')),
                ('localisation', models.CharField(max_length=200, verbose_name='localisation')),
                ('duree_mois', models.IntegerField(default=3, verbose_name='durée en mois')),
                ('description', models.TextField(verbose_name='description')),
                ('profil_recherche', models.TextField(verbose_name='profil recherché')),
                ('competences_requises', models.TextField(verbose_name='compétences requises')),
                ('missions', models.TextField(verbose_name='missions')),
                ('avantages', models.TextField(blank=True, verbose_name='avantages')),
                ('conditions', models.TextField(blank=True, verbose_name='conditions')),
                ('remuneration', models.CharField(blank=True, max_length=100, verbose_name='rémunération')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin_candidature', models.DateField(verbose_name='date limite de candidature')),
                ('contact_nom', models.CharField(max_length=100, verbose_name='nom du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone du contact')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('draft', 'Brouillon'), ('expired', 'Expirée')], default='open', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('vues', models.IntegerField(default=0, verbose_name='nombre de vues')),
                ('candidatures', models.IntegerField(default=0, verbose_name='nombre de candidatures')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'offre de stage',
                'verbose_name_plural': 'offres de stage',
                'db_table': 'offre_stage',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
