# Generated by Django 4.2.7 on 2025-07-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0002_add_offrestage_fields'),
        ('shared', '0003_offrestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrestage',
            name='reference_pfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_stage', to='admin_service.pfeproject', verbose_name='référence PFE'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='type',
            field=models.CharField(choices=[('PFE', 'PFE'), ('Classique', 'Classique')], default='Classique', max_length=20, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validée'),
        ),
    ]
