# Generated by Django 4.2.7 on 2025-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_add_offrestage_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offrestage',
            options={'ordering': ['-id'], 'verbose_name': 'offre de stage', 'verbose_name_plural': 'offres de stage'},
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='avantages',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='candidatures',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='competences_requises',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='contact_nom',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='contact_telephone',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='date_fin_candidature',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='duree_mois',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='missions',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='profil_recherche',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='reference_pfe',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='remuneration',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='offrestage',
            name='vues',
        ),
        migrations.AddField(
            model_name='offrestage',
            name='diplome',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='diplôme'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='keywords',
            field=models.TextField(blank=True, default='Inconnu', verbose_name='mots clés'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='nombre_postes',
            field=models.PositiveIntegerField(default=1, verbose_name='nombre de postes'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='objectifs',
            field=models.TextField(blank=True, default='Inconnu', verbose_name='objectifs'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='reference',
            field=models.CharField(default='Inconnu', max_length=50, unique=True, verbose_name='référence'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='title',
            field=models.CharField(default='Inconnu', max_length=200, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='ville',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='description',
            field=models.TextField(default='Inconnu', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='specialite',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='spécialité'),
        ),
    ]
