# Generated by Django 4.2.7 on 2025-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_alter_offrestage_options_remove_offrestage_avantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrestage',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('draft', 'Brouillon'), ('expired', 'Expirée')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='type',
            field=models.CharField(choices=[('Classique', 'Classique'), ('PFE', 'PFE')], default='Classique', max_length=20, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validée'),
        ),
    ]
