# Generated by Django 4.2.7 on 2025-07-29 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0006_offrestage_status_offrestage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('abstract', models.TextField(blank=True, verbose_name='résumé')),
                ('keywords', models.TextField(blank=True, verbose_name='mots-clés')),
                ('speciality', models.CharField(max_length=200, verbose_name='spécialité')),
                ('year', models.IntegerField(default=2025, verbose_name='année')),
                ('pdf_file', models.FileField(upload_to='pfe_reports/', verbose_name='rapport PDF')),
                ('presentation_file', models.FileField(blank=True, upload_to='pfe_presentations/', verbose_name='présentation')),
                ('additional_files', models.FileField(blank=True, upload_to='pfe_additional/', verbose_name='fichiers additionnels')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', 'En cours de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='date de soumission')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de révision')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'approbation")),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'archivage")),
                ('tuteur_feedback', models.TextField(blank=True, verbose_name='feedback tuteur')),
                ('stagiaire_comment', models.TextField(blank=True, verbose_name='commentaire stagiaire')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='raison du rejet')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('is_final', models.BooleanField(default=False, verbose_name='version finale')),
                ('download_count', models.IntegerField(default=0, verbose_name='nombre de téléchargements')),
                ('view_count', models.IntegerField(default=0, verbose_name='nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pfe_report', to='shared.stage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfe_reports', to=settings.AUTH_USER_MODEL)),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfe_reports_tuteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rapport PFE',
                'verbose_name_plural': 'rapports PFE',
                'db_table': 'pfe_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
