# Generated by Django 4.2.7 on 2025-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_add_pfe_report_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfereport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pfe_reports/', verbose_name='rapport PDF'),
        ),
    ]
