# Generated by Django 4.2.7 on 2025-08-01 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0008_alter_pfereport_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('target_type', models.CharField(choices=[('all_stagiaires', 'Tous les stagiaires'), ('specific_stagiaires', 'Stagiaires spécifiques'), ('by_institute', 'Par institut'), ('by_speciality', 'Par spécialité')], default='all_stagiaires', max_length=20, verbose_name='type de cible')),
                ('target_institutes', models.JSONField(blank=True, default=list, verbose_name='instituts cibles')),
                ('target_specialities', models.JSONField(blank=True, default=list, verbose_name='spécialités cibles')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='début programmé')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='fin programmée')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='début réel')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='fin réelle')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Fermé'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('kpi_threshold_warning', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name="seuil d'alerte")),
                ('kpi_threshold_critical', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='seuil critique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('target_stagiaires', models.ManyToManyField(blank=True, limit_choices_to={'role': 'stagiaire'}, related_name='assigned_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sondage',
                'verbose_name_plural': 'sondages',
                'db_table': 'survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_responses', models.IntegerField(default=0, verbose_name='total réponses')),
                ('response_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de réponse')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='score moyen')),
                ('category_averages', models.JSONField(blank=True, default=dict, verbose_name='moyennes par catégorie')),
                ('critical_alerts', models.IntegerField(default=0, verbose_name='alertes critiques')),
                ('warning_alerts', models.IntegerField(default=0, verbose_name="alertes d'avertissement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_dashboard', to='shared.survey')),
            ],
            options={
                'verbose_name': 'tableau de bord KPI',
                'verbose_name_plural': 'tableaux de bord KPI',
                'db_table': 'kpi_dashboard',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, verbose_name='réponses')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score global')),
                ('category_scores', models.JSONField(blank=True, default=dict, verbose_name='scores par catégorie')),
                ('is_completed', models.BooleanField(default=False, verbose_name='terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de completion')),
                ('additional_comments', models.TextField(blank=True, verbose_name='commentaires additionnels')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='shared.survey')),
            ],
            options={
                'verbose_name': 'réponse au sondage',
                'verbose_name_plural': 'réponses au sondage',
                'db_table': 'survey_response',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'stagiaire')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='question')),
                ('question_type', models.CharField(choices=[('rating', 'Évaluation (1-5)'), ('text', 'Texte libre'), ('choice', 'Choix multiple'), ('boolean', 'Oui/Non')], default='rating', max_length=20, verbose_name='type de question')),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('soft_skills', 'Soft Skills'), ('communication', 'Communication'), ('teamwork', "Travail d'équipe"), ('leadership', 'Leadership'), ('adaptability', 'Adaptabilité'), ('satisfaction', 'Satisfaction'), ('other', 'Autre')], default='other', max_length=20, verbose_name='catégorie')),
                ('order', models.IntegerField(default=0, verbose_name='ordre')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='choix')),
                ('kpi_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='poids KPI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shared.survey')),
            ],
            options={
                'verbose_name': 'question de sondage',
                'verbose_name_plural': 'questions de sondage',
                'db_table': 'survey_question',
                'ordering': ['order'],
                'unique_together': {('survey', 'order')},
            },
        ),
    ]
