# Generated by Django 4.2.7 on 2025-08-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_add_survey_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('secteur_activite', models.CharField(blank=True, max_length=200, verbose_name="secteur d'activité")),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('pays', models.CharField(default='Maroc', max_length=100, verbose_name='pays')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'db_table': 'entreprise',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='stage',
            name='company',
        ),
        migrations.AddField(
            model_name='stage',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom entreprise'),
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='type',
            field=models.CharField(choices=[('PFE', 'PFE')], default='PFE', max_length=20, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='offrestage',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_stage', to='shared.entreprise', verbose_name='entreprise'),
        ),
        migrations.AddField(
            model_name='stage',
            name='company_entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='shared.entreprise', verbose_name='entreprise'),
        ),
    ]
