# Generated by Django 4.2.7 on 2025-08-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demande_service', '0006_demande_entreprise_demandeoffre_entreprise_and_more'),
        ('shared', '0010_entreprise_remove_stage_company_stage_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_demandes_soumises', models.PositiveIntegerField(default=0, verbose_name='nombre de demandes soumises')),
                ('nombre_demandes_max', models.PositiveIntegerField(default=4, verbose_name='nombre maximum de demandes')),
                ('institut', models.CharField(blank=True, max_length=200, verbose_name='institut')),
                ('specialite', models.CharField(blank=True, max_length=200, verbose_name='spécialité')),
                ('niveau', models.CharField(blank=True, max_length=100, verbose_name='niveau')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='profil LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='portfolio')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('date_derniere_demande', models.DateTimeField(blank=True, null=True, verbose_name='date de dernière demande')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidat',
                'verbose_name_plural': 'candidats',
                'db_table': 'candidat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', 'En cours de révision'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='pending', max_length=20, verbose_name='statut')),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/', verbose_name='CV')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidatures/lettres/', verbose_name='lettre de motivation')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='candidatures/autres/', verbose_name='autres documents')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('raison_refus', models.TextField(blank=True, verbose_name='raison du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de révision')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='shared.candidat')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='demande_service.demande')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='shared.offrestage')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'db_table': 'candidature',
                'ordering': ['-created_at'],
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
