# Generated by Django 4.2.7 on 2025-08-16 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0011_candidat_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='institut',
            field=models.CharField(max_length=200, verbose_name='institut'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau',
            field=models.CharField(max_length=100, verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nombre_demandes_max',
            field=models.PositiveIntegerField(default=3, verbose_name='nombre maximum de demandes'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='URL Portfolio'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='specialite',
            field=models.CharField(max_length=200, verbose_name='spécialité'),
        ),
    ]
