# Generated by Django 4.2.7 on 2025-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_candidature_reviewed_by_alter_candidat_institut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='nombre_demandes_max',
            field=models.PositiveIntegerField(default=4, verbose_name='nombre maximum de demandes'),
        ),
    ]
