# Generated by Django 4.2.7 on 2025-08-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_update_candidat_max_demandes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['nom'], 'verbose_name': 'filiale', 'verbose_name_plural': 'filiales'},
        ),
        migrations.AlterField(
            model_name='offrestage',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_stage', to='shared.entreprise', verbose_name='filiale'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='company_entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='shared.entreprise', verbose_name='filiale'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom filiale'),
        ),
    ]
