# Generated by Django 5.0.2 on 2025-07-05 13:38

import auth_service.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_service.models.UserManager()),
            ],
        ),
    ]
