# Generated by Django 4.2.7 on 2025-08-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_entreprise_remove_stage_company_stage_company_name_and_more'),
        ('auth_service', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shared.entreprise', verbose_name='entreprise'),
        ),
    ]
