# Generated by Django 4.2.7 on 2025-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('stagiaire', 'Stagiaire'),
                    ('rh', 'RH'),
                    ('tuteur', 'Tuteur'),
                    ('admin', 'Admin'),
                    ('candidat', 'Candidat')
                ],
                default='stagiaire',
                max_length=20,
                verbose_name='rôle'
            ),
        ),
    ]
