# Generated by Django 4.2.7 on 2025-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_fix_candidat_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_applications',
            field=models.PositiveIntegerField(default=3, verbose_name='nombre maximum de candidatures'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_applications',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre total de candidatures'),
        ),
    ]
