"""
© 2025 Mohamed Amine FRAD. All rights reserved.
Unauthorized use, reproduction, or modification of this code is strictly prohibited.
Intellectual Property – Protected by international copyright law.
"""

# Generated by Django 4.2.7 on 2025-01-27 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('system', 'System Event'), ('user_action', 'User Action'), ('stage_update', 'Stage Update'), ('document_upload', 'Document Upload'), ('evaluation', 'Evaluation'), ('survey', 'Survey'), ('testimonial', 'Testimonial'), ('demande', 'Demande'), ('kpi_alert', 'KPI Alert')], max_length=20, verbose_name='type d\'événement')),
                ('event_data', models.JSONField(default=dict, verbose_name='données de l\'événement')),
                ('processed', models.BooleanField(default=False, verbose_name='traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'événement de notification',
                'verbose_name_plural': 'événements de notification',
                'db_table': 'notification_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('title_template', models.CharField(max_length=200, verbose_name='modèle de titre')),
                ('message_template', models.TextField(verbose_name='modèle de message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=10, verbose_name='type de notification')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'modèle de notification',
                'verbose_name_plural': 'modèles de notification',
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=255, unique=True, verbose_name='ID de connexion')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'connexion WebSocket',
                'verbose_name_plural': 'connexions WebSocket',
                'db_table': 'websocket_connection',
            },
        ),
    ]
