# Generated by Django 4.2.7 on 2025-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketconnection',
            name='connection_id',
            field=models.CharField(max_length=191, unique=True, verbose_name='ID de connexion'),
        ),
    ]
