# Generated by Django 4.2.7 on 2025-07-07 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfeproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfe_projects_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
