# Generated by Django 4.2.7 on 2025-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0002_add_offrestage_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfeproject',
            options={'ordering': ['-id'], 'verbose_name': 'projet PFE', 'verbose_name_plural': 'projets PFE'},
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='current_candidates',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='max_candidates',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='supervisor_department',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='supervisor_email',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='supervisor_name',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='pfeproject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pfeproject',
            name='diplome',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='diplôme'),
        ),
        migrations.AddField(
            model_name='pfeproject',
            name='keywords',
            field=models.TextField(blank=True, default='Inconnu', verbose_name='mots clés'),
        ),
        migrations.AddField(
            model_name='pfeproject',
            name='nombre_postes',
            field=models.PositiveIntegerField(default=1, verbose_name='nombre de postes'),
        ),
        migrations.AddField(
            model_name='pfeproject',
            name='specialite',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='spécialité'),
        ),
        migrations.AddField(
            model_name='pfeproject',
            name='ville',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='pfeproject',
            name='description',
            field=models.TextField(default='Inconnu', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pfeproject',
            name='objectives',
            field=models.TextField(blank=True, default='Inconnu', verbose_name='objectifs'),
        ),
        migrations.AlterField(
            model_name='pfeproject',
            name='reference_id',
            field=models.CharField(default='Inconnu', max_length=50, unique=True, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='pfeproject',
            name='title',
            field=models.CharField(default='Inconnu', max_length=200, verbose_name='titre'),
        ),
    ]
