# Generated by Django 5.0.2 on 2025-07-04 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('cin', models.CharField(max_length=20, verbose_name='CIN')),
                ('institut', models.CharField(max_length=200, verbose_name='institut')),
                ('specialite', models.CharField(max_length=200, verbose_name='spécialité')),
                ('type_stage', models.CharField(choices=[('Stage PFE', 'Stage PFE'), ("Stage d'Été", "Stage d'Été"), ("Stage d'Observation", "Stage d'Observation"), ("Stage de Fin d'Études", "Stage de Fin d'Études")], max_length=50, verbose_name='type de stage')),
                ('niveau', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], max_length=20, verbose_name='niveau')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('stage_binome', models.BooleanField(default=False, verbose_name='stage en binôme')),
                ('nom_binome', models.CharField(blank=True, max_length=100, verbose_name='nom du binôme')),
                ('prenom_binome', models.CharField(blank=True, max_length=100, verbose_name='prénom du binôme')),
                ('email_binome', models.EmailField(blank=True, max_length=254, verbose_name='email du binôme')),
                ('telephone_binome', models.CharField(blank=True, max_length=20, verbose_name='téléphone du binôme')),
                ('cin_binome', models.CharField(blank=True, max_length=20, verbose_name='CIN du binôme')),
                ('cv', models.FileField(blank=True, null=True, upload_to='demandes/cv/', verbose_name='CV')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='demandes/lettres/', verbose_name='lettre de motivation')),
                ('demande_stage', models.FileField(blank=True, null=True, upload_to='demandes/demandes/', verbose_name='demande de stage')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut')),
                ('raison_refus', models.TextField(blank=True, verbose_name='raison du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de stage',
                'verbose_name_plural': 'demandes de stage',
                'db_table': 'demande_stage',
                'ordering': ['-created_at'],
            },
        ),
    ]
