# Generated by Django 5.0.2 on 2025-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='cv_binome',
            field=models.FileField(blank=True, null=True, upload_to='demandes/cv/', verbose_name='CV binôme'),
        ),
        migrations.AddField(
            model_name='demande',
            name='demande_stage_binome',
            field=models.FileField(blank=True, null=True, upload_to='demandes/demandes/', verbose_name='demande de stage binôme'),
        ),
        migrations.AddField(
            model_name='demande',
            name='lettre_motivation_binome',
            field=models.FileField(blank=True, null=True, upload_to='demandes/lettres/', verbose_name='lettre de motivation binôme'),
        ),
        migrations.AddField(
            model_name='demande',
            name='pfe_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='référence PFE'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='niveau',
            field=models.CharField(max_length=100, verbose_name='niveau'),
        ),
    ]
