# Generated by Django 4.2.7 on 2025-07-24 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_offrestage_status_offrestage_type_and_more'),
        ('demande_service', '0002_demande_cv_binome_demande_demande_stage_binome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_offres', to='demande_service.demande')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_demandes', to='shared.offrestage')),
            ],
            options={
                'unique_together': {('demande', 'offre')},
            },
        ),
        migrations.AddField(
            model_name='demande',
            name='offres',
            field=models.ManyToManyField(blank=True, related_name='demandes', through='demande_service.DemandeOffre', to='shared.offrestage'),
        ),
    ]
