# Generated by Django 4.2.7 on 2025-07-31 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande_service', '0003_demandeoffre_demande_offres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='cin_binome',
        ),
    ]
