# Generated by Django 4.2.7 on 2025-08-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_entreprise_remove_stage_company_stage_company_name_and_more'),
        ('demande_service', '0005_add_date_soumission'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='shared.entreprise', verbose_name='entreprise'),
        ),
        migrations.AddField(
            model_name='demandeoffre',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_offres', to='shared.entreprise', verbose_name='entreprise'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_soumission',
            field=models.DateField(auto_now_add=True, help_text='Date automatique de soumission de la demande', verbose_name='date de soumission'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_stage',
            field=models.CharField(choices=[('Stage PFE', 'Stage PFE')], max_length=50, verbose_name='type de stage'),
        ),
    ]
