# Generated by Django 4.2.7 on 2025-08-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demande_service', '0006_demande_entreprise_demandeoffre_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('interview_scheduled', "En attente d'entretien"), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='heure')),
                ('location', models.CharField(max_length=500, verbose_name='lieu')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='statut')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email envoyé')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='demande_service.demande')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_scheduled', to=settings.AUTH_USER_MODEL, verbose_name='planifié par')),
            ],
            options={
                'verbose_name': 'entretien',
                'verbose_name_plural': 'entretiens',
                'db_table': 'interview',
                'ordering': ['-created_at'],
            },
        ),
    ]
