# Generated by Django 4.2.7 on 2025-08-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_alter_entreprise_options_alter_offrestage_entreprise_and_more'),
        ('demande_service', '0007_alter_demande_status_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='shared.entreprise', verbose_name='filiale'),
        ),
        migrations.AlterField(
            model_name='demandeoffre',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_offres', to='shared.entreprise', verbose_name='filiale'),
        ),
    ]
