# Generated by Django 4.2.7 on 2025-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_service', '0009_interview_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
