# Generated by Django 4.2.7 on 2025-08-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_alter_entreprise_options_alter_offrestage_entreprise_and_more'),
        ('demande_service', '0010_alter_interviewrequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewrequest',
            name='alternative_date',
        ),
        migrations.RemoveField(
            model_name='interviewrequest',
            name='alternative_time',
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='filiale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='shared.entreprise', verbose_name='filiale'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='suggested_date',
            field=models.DateField(blank=True, null=True, verbose_name='date suggérée'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True, verbose_name='heure suggérée'),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_TUTEUR', 'En attente du tuteur'), ('VALIDATED', 'Validé'), ('REVISION_REQUESTED', 'Révision demandée')], default='PENDING_TUTEUR', max_length=30, verbose_name='statut'),
        ),
    ]
