# Generated by Django 4.2.7 on 2025-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande_service', '0011_update_interview_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='lien de réunion'),
        ),
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Présentiel'), ('online', 'En ligne')], default='in_person', max_length=20, verbose_name='mode'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='lien de réunion'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='mode',
            field=models.CharField(choices=[('in_person', 'Présentiel'), ('online', 'En ligne')], default='in_person', max_length=20, verbose_name='mode'),
        ),
    ]
